// Central mock events dataset used by both list and detail endpoints.
// In a real application this would be replaced with database access.
export const events = [
  {
    id: 'e1',
    title: 'Jazz Night with Sarah Connor',
    category: 'music',
    startsAt: '2025-08-20T19:30:00Z',
    venue: 'Blue Note Jazz Club',
    remainingSeats: 42,
    description: 'An intimate evening of contemporary jazz featuring renowned pianist Sarah Connor and her quartet.',
    poster: '/images/events/jazz-night.jpg',
    price: 45,
    duration: 120,
  },
  {
    id: 'e2',
    title: 'Tech Innovation Conference 2025',
    category: 'conference',
    startsAt: '2025-08-25T09:00:00Z',
    venue: 'Convention Center Hall A',
    remainingSeats: 150,
    description: 'Join industry leaders as they discuss the latest trends in AI, blockchain, and sustainable technology.',
    poster: '/images/events/tech-conf.jpg',
    price: 120,
    duration: 480,
  },
  {
    id: 'e3',
    title: 'Shakespeare in the Park: Hamlet',
    category: 'theater',
    startsAt: '2025-08-22T20:00:00Z',
    venue: 'Central Park Amphitheater',
    remainingSeats: 25,
    description: 'Experience the timeless tragedy of Hamlet in a beautiful outdoor setting under the stars.',
    poster: '/images/events/hamlet.jpg',
    price: 35,
    duration: 180,
  },
  {
    id: 'e4',
    title: 'Modern Art Workshop',
    category: 'workshop',
    startsAt: '2025-08-28T14:00:00Z',
    venue: 'Creative Arts Studio',
    remainingSeats: 8,
    description: 'Learn contemporary painting techniques with award-winning artist Maria Rodriguez.',
    poster: '/images/events/art-workshop.jpg',
    price: 75,
    duration: 240,
  },
  {
    id: 'e5',
    title: 'Stand-up Comedy Night',
    category: 'comedy',
    startsAt: '2025-08-30T21:00:00Z',
    venue: 'Laugh Track Comedy Club',
    remainingSeats: 60,
    description: "Get ready to laugh with three of the city's funniest comedians in one unforgettable night.",
    poster: '/images/events/comedy-night.jpg',
    price: 25,
    duration: 90,
  },
  {
    id: 'e6',
    title: 'Wine Tasting Experience',
    category: 'food',
    startsAt: '2025-09-02T18:00:00Z',
    venue: 'Vintage Wine Bar',
    remainingSeats: 20,
    description: 'Discover exceptional wines from around the world guided by our sommelier expert.',
    poster: '/images/events/wine-tasting.jpg',
    price: 85,
    duration: 150,
  },
  {
    id: 'e7',
    title: 'Yoga & Mindfulness Retreat',
    category: 'wellness',
    startsAt: '2025-09-05T08:00:00Z',
    venue: 'Serenity Wellness Center',
    remainingSeats: 15,
    description: 'Rejuvenate your mind and body with guided yoga sessions and meditation practices.',
    poster: '/images/events/yoga-retreat.jpg',
    price: 95,
    duration: 300,
  },
  {
    id: 'e8',
    title: 'Classic Rock Tribute Band',
    category: 'music',
    startsAt: '2025-09-08T19:00:00Z',
    venue: 'Rock Arena',
    remainingSeats: 200,
    description: 'Relive the golden age of rock with tribute performances of Led Zeppelin, Queen, and The Beatles.',
    poster: '/images/events/rock-tribute.jpg',
    price: 55,
    duration: 150,
  },
  {
    id: 'e9',
    title: 'Digital Marketing Masterclass',
    category: 'conference',
    startsAt: '2025-09-10T10:00:00Z',
    venue: 'Business Innovation Hub',
    remainingSeats: 80,
    description: 'Master the latest digital marketing strategies and tools used by Fortune 500 companies.',
    poster: '/images/events/marketing-class.jpg',
    price: 150,
    duration: 360,
  },
  {
    id: 'e10',
    title: 'Film Festival Opening Night',
    category: 'film',
    startsAt: '2025-09-12T19:30:00Z',
    venue: 'Grand Cinema Theater',
    remainingSeats: 300,
    description: 'Celebrate independent cinema with premieres, director Q&As, and networking opportunities.',
    poster: '/images/events/film-festival.jpg',
    price: 40,
    duration: 240,
  },
  {
    id: 'e11',
    title: 'Cooking Class: Italian Cuisine',
    category: 'workshop',
    startsAt: '2025-09-15T16:00:00Z',
    venue: 'Culinary Institute',
    remainingSeats: 12,
    description: 'Learn to prepare authentic Italian dishes from a Michelin-starred chef.',
    poster: '/images/events/cooking-italian.jpg',
    price: 120,
    duration: 180,
  },
  {
    id: 'e12',
    title: 'Blues & BBQ Festival',
    category: 'music',
    startsAt: '2025-09-18T12:00:00Z',
    venue: 'Riverside Park',
    remainingSeats: 500,
    description: 'Enjoy live blues music, craft beer, and authentic BBQ in a family-friendly outdoor setting.',
    poster: '/images/events/blues-bbq.jpg',
    price: 30,
    duration: 420,
  },
];
