[tool.ruff]
# lint 규칙을 활성화합니다. E, F, W는 각각 Error, Flake8, Warning의 약자입니다.
# I는 import 관련 규칙입니다.
select = ["E", "F", "W", "I"]

# 특정 규칙을 무시합니다.
# E501: 한 줄이 88자 이상일 때 발생하는 오류를 무시 (Black 포매터와 호환)
ignore = ["E501"]

# 한 줄의 최대 길이를 설정합니다. (Black 포매터와 맞추기)
line-length = 88