# Generated by Django 5.2.5 on 2025-08-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveIntegerField()),
                ('col', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('available', 'available'), ('reserved', 'reserved')], default='available', help_text='available(예약 가능) / reserved(예약됨)', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['row', 'col'],
                'indexes': [models.Index(fields=['row', 'col'], name='seats_seat_row_f82c62_idx'), models.Index(fields=['status'], name='seats_seat_status_241077_idx')],
                'unique_together': {('row', 'col')},
            },
        ),
    ]
