# Generated by Django 5.2.5 on 2025-08-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0002_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='reserver_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='seat',
            name='reserver_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
