[package]
name = "config-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
name = "config_api"
path = "src/lib.rs"

[dependencies]
once_cell.workspace = true
salvo.workspace = true

seat-controller = { path = "../../seat/controller" }